stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_REGISTRY_BASE: $CI_REGISTRY_IMAGE
  DOCKER_TLS_CERTDIR: "/certs"
  SWARM_FOLDER: /mnt/cephfs/swarm/stacks/cal.minet.net
  DOCKER_BUILDKIT: 1

services:
  - docker:dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

build_backend:
  stage: build
  image: docker:latest
  script:
    - cd backend
    - docker pull $IMAGE_REGISTRY_BASE/backend:stable || true
    - docker build --cache-from $IMAGE_REGISTRY_BASE/backend:stable --build-arg BUILDKIT_INLINE_CACHE=1 -f Dockerfile.prod -t $IMAGE_REGISTRY_BASE/backend:stable .
    - docker push $IMAGE_REGISTRY_BASE/backend:stable

build_nginx:
  stage: build
  image: docker:latest
  script:
    - docker pull $IMAGE_REGISTRY_BASE/nginx:stable || true
    - docker build --cache-from $IMAGE_REGISTRY_BASE/nginx:stable --build-arg BUILDKIT_INLINE_CACHE=1 -f nginx/Dockerfile -t $IMAGE_REGISTRY_BASE/nginx:stable .
    - docker push $IMAGE_REGISTRY_BASE/nginx:stable

deploy_prod:
  stage: deploy
  image: docker:latest
  tags:
    - swarm
  script:
    - chmod +x deploy.sh
    - mkdir -p $SWARM_FOLDER
    - cp stack.yaml $SWARM_FOLDER/
    - cp deploy.sh $SWARM_FOLDER/
    - cd $SWARM_FOLDER
    - echo "IMAGE_REGISTRY_BASE=$IMAGE_REGISTRY_BASE" > .env.deploy
    - echo "CI_REGISTRY_USER=$CI_REGISTRY_USER" >> .env.deploy
    - echo "CI_REGISTRY_PASSWORD=$CI_REGISTRY_PASSWORD" >> .env.deploy
    - ./deploy.sh
  only:
    - main
